flowchart TB
  ACT-001["Vendita Cappuccino (2 min)"]
  ACT_001_H_0(["Cameriere (€15/h)"])
  ACT-001 --> ACT_001_H_0
  ACT-001 --> ACT-002
  ACT-002["Assemblaggio (1 min)"]
  ACT-002 --> ACT-003
  ACT-002 --> ACT-004
  ACT-003["Preparazione Caffè (1 min)"]
  ACT_003_M_0[/"Miscela (€7.20)"/]
  ACT-003 --> ACT_003_M_0
  ACT_003_SUP_M_0{"Fornitore Caffè: max 50000.0/mese [validatore]"}
  ACT_003_M_0 -.-> ACT_003_SUP_M_0
  ACT-004["Montatura Latte (3 min)"]
  ACT_004_H_0(["Barista (€20/h)"])
  ACT-004 --> ACT_004_H_0
  ACT_004_M_0[/"Latte (€22.50)"/]
  ACT-004 --> ACT_004_M_0
  ACT_004_SUP_M_0{"Fornitore Latte: max 200000.0/settimana [validatore]"}
  ACT_004_M_0 -.-> ACT_004_SUP_M_0
  style ACT-001 fill:#f96,stroke:#333
  style ACT-002 fill:#f96,stroke:#333
  style ACT-004 fill:#f96,stroke:#333
